# Generated by Django 3.2.17 on 2023-04-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nm_category_en_us',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='nm_category_ru',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        # migrations.DeleteModel(
        #     name='Subscription',
        # ),
    ]
