# Generated by Django 3.2.17 on 2023-04-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20230424_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_text_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        # migrations.DeleteModel(
        #     name='Subscription',
        # ),
    ]
